<a href="https://colab.research.google.com/github/virf96/Basico/blob/main/Calidad_de_datos_%7C_OLAP_%26OLTP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
pd.set_option("display.max_columns",200)

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df=pd.read_csv("/content/drive/My Drive/datasets/datos_mustra_1.csv",)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (2,10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

,edad,minutos,monto_de_apoyo,horas,ent_regis,mun_regis,ent_resid,mun_resid,ent_ocurr,mun_ocurr,sexo,ocupacion,edo_civil,lugar_ocur,sitio_ocur,nacionalid,embarazo,grupo,lengua,clave,escolarida,fecha_nac,fecha_ocurr,programa_fondo,nombre_del_proyecto,nombre_del_beneficiario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,8,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,8,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n

In [5]:
#Veamos las dimensiones del data frame
df.shape

(655341, 26)

In [6]:
#Ahora las características de las variables
df.dtypes

edad                         int64
minutos                      int64
monto_de_apoyo              object
horas                        int64
ent_regis                  float64
mun_regis                    int64
ent_resid                    int64
mun_resid                    int64
ent_ocurr                  float64
mun_ocurr                    int64
sexo                        object
ocupacion                    int64
edo_civil                  float64
lugar_ocur                   int64
sitio_ocur                   int64
nacionalid                   int64
embarazo                     int64
grupo                        int64
lengua                     float64
clave                        int64
escolarida                   int64
fecha_nac                   object
fecha_ocurr                 object
programa_fondo              object
nombre_del_proyecto         object
nombre_del_beneficiario     object
dtype: object

In [7]:
#Identificamos is hay duplicados
df.duplicated().sum()

8

In [8]:
#Borramos los duplicados
df.drop_duplicates(inplace=True)

In [9]:
#Verificamos el cambio
df.duplicated().sum()

0

In [10]:
#Identificamos los niveles de la variable y su frecuencia dentro del df
df["edad"].value_counts()

4084    14900
4079    14778
4085    14515
4080    14378
4081    14047
        ...
4120        2
4117        2
4116        1
3098        1
2098        1
Name: edad, Length: 187, dtype: int64

In [12]:
#Nombre de las columnas
df.columns

Index(['edad', 'minutos', 'monto_de_apoyo', 'horas', 'ent_regis', 'mun_regis',
       'ent_resid', 'mun_resid', 'ent_ocurr', 'mun_ocurr', 'sexo', 'ocupacion',
       'edo_civil', 'lugar_ocur', 'sitio_ocur', 'nacionalid', 'embarazo',
       'grupo', 'lengua', 'clave', 'escolarida', 'fecha_nac', 'fecha_ocurr',
       'programa_fondo', 'nombre_del_proyecto', 'nombre_del_beneficiario'],
      dtype='object')

In [13]:
#Estadística descriptiva
df.describe()

,edad,minutos,horas,ent_regis,mun_regis,ent_resid,mun_resid,ent_ocurr,mun_ocurr,ocupacion,edo_civil,lugar_ocur,sitio_ocur,nacionalid,embarazo,grupo,lengua,clave,escolarida
count,655333.000000,655333.000000,655333.000000,458941.000000,655333.000000,655333.000000,655333.000000,0.0,655333.000000,655333.000000,0.0,655333.000000,655333.000000,655333.000000,655333.000000,655333.000000,151164.000000,655333.000000,655333.000000
mean,3995.239106,21.949548,12.679938,16.540176,51.515352,16.672460,55.592775,NaN,51.820590,20.473089,NaN,79.271650,9.275178,1.005861,8.006821,6.567649,3.114637,6566.704378,11.887530
std,401.392086,19.509928,11.413132,8.149956,64.580768,8.121961,85.946842,NaN,73.016475,30.057434,NaN,25.557792,13.491876,0.076333,0.488400,6.230990,2.683850,140.182072,25.584275
min,1001.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,NaN,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6343.000000,1.000000
25%,4051.000000,0.000000,6.000000,9.000000,14.000000,10.000000,12.000000,NaN,12.000000,7.000000,NaN,88.000000,3.000000,1.000000,8.000000,2.000000,2.000000,6473.000000,3.000000
50%,4069.000000,20.000000,12.000000,15.000000,33.000000,15.000000,33.000000,NaN,32.000000,11.000000,NaN,88.000000,11.000000,1.000000,8.000000,4.000000,2.000000,6540.000000,4.000000
75%,4082.000000,35.000000,18.000000,22.000000,67.000000,23.000000,70.000000,NaN,67.000000,11.000000,NaN,88.000000,11.000000,1.000000,8.000000,8.000000,2.000000,6689.000000,6.000000
max,4998.000000,99.000000,99.000000,32.000000,570.000000,35.000000,999.000000,NaN,999.000000,99.000000,NaN,88.000000,99.000000,2.000000,9.000000,34.000000,9.000000,6897.000000,99.000000

In [14]:
df.head()

,edad,minutos,monto_de_apoyo,horas,ent_regis,mun_regis,ent_resid,mun_resid,ent_ocurr,mun_ocurr,sexo,ocupacion,edo_civil,lugar_ocur,sitio_ocur,nacionalid,embarazo,grupo,lengua,clave,escolarida,fecha_nac,fecha_ocurr,programa_fondo,nombre_del_proyecto,nombre_del_beneficiario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,8,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,8,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n

In [15]:
#Identificamos los niveles de la variable y la frecuencia
df["sexo"].value_counts()

1                                       307728
2                                       249075
1                                        55826
2                                        42376
9                                          253
9                                           65
Molina Pasquel Y Henriquez                   2
MARICELA  LOPEZ CEPEDA\n                     2
SFERP S.C.                                   2
Sistema Tecnológico de Jalisco, A.C.         2
Name: sexo, dtype: int64

In [16]:
#Agrupamos las variables de acuerdo a su tipo de variable
c_feats=["edad","minutos","monto_de_apoyo","horas"]
v_feats=["ent_regis","mun_regis","ent_resid","mun_resid","ent_ocurr","mun_ocurr","sexo","ocupacion","edo_civil",
        "lugar_ocur","sitio_ocur","nacionalid","embarazo","grupo","lengua","clave","escolarida"]
d_feats=["fecha_nac","fecha_ocurr"]
t_feats=["programa_fondo","nombre_del_proyecto","nombre_del_beneficiario"]

In [17]:
c_feats_new=["c_"+x for x in c_feats]
v_feats_new=["v_"+x for x in v_feats]
d_feats_new=["d_"+x for x in d_feats]
t_feats_new=["t_"+x for x in t_feats]

In [18]:
c_feats_new

['c_edad', 'c_minutos', 'c_monto_de_apoyo', 'c_horas']

In [19]:
#Renombramos las variables
df.rename(columns=dict(zip(d_feats,d_feats_new)),inplace=True)
df.rename(columns=dict(zip(v_feats,v_feats_new)),inplace=True)
df.rename(columns=dict(zip(t_feats,t_feats_new)),inplace=True)
df.rename(columns=dict(zip(c_feats,c_feats_new)),inplace=True)

In [20]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_sexo,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario
0,4069,27,NaN,16,1.0,1,1,1,NaN,1,NaN,11,NaN,88,3,1,8,7,2.0,6343,1,1946-06-30,2015-05-25,Programa Jalisciense de Fomento a la Propieda...,MX - SISTEMA MECATRÓNICO PARA EL CONTROL DE IN...,RICARDO MERCADO CORTÉS\n
1,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n
2,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.
3,4047,58,"Sistema Tecnológico de Jalisco, A.C.",3,NaN,1,1,1,NaN,1,"Sistema Tecnológico de Jalisco, A.C.",7,NaN,88,9,1,8,13,1.0,6346,6,1967-08-28,2015-01-03,Programa Jalisciense de Fomento a la Propieda...,MX-PASTA BIODEGRADABLE PARA USOS MÚLTIPLES\n,CORPORATIVO BORO S.A. DE C.V.\n
4,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n

In [21]:
df.isnull().sum()/df.shape[0]

c_edad                       0.000000
c_minutos                    0.000000
c_monto_de_apoyo             0.000003
c_horas                      0.000000
v_ent_regis                  0.299683
v_mun_regis                  0.000000
v_ent_resid                  0.000000
v_mun_resid                  0.000000
v_ent_ocurr                  1.000000
v_mun_ocurr                  0.000000
v_sexo                       0.000003
v_ocupacion                  0.000000
v_edo_civil                  1.000000
v_lugar_ocur                 0.000000
v_sitio_ocur                 0.000000
v_nacionalid                 0.000000
v_embarazo                   0.000000
v_grupo                      0.000000
v_lengua                     0.769333
v_clave                      0.000000
v_escolarida                 0.000000
d_fecha_nac                  0.015836
d_fecha_ocurr                0.000217
t_programa_fondo             0.000000
t_nombre_del_proyecto        0.000000
t_nombre_del_beneficiario    0.000000
dtype: float64

In [22]:
sexo=pd.read_csv("/content/drive/My Drive/datasets/desexo.csv")
ocupacion=pd.read_csv("/content/drive/My Drive/datasets/deocupa.csv")
escolaridad=pd.read_csv("/content/drive/My Drive/datasets/deesco.csv")
edad=pd.read_csv("/content/drive/My Drive/datasets/deedad.csv")

In [23]:
sexo.head()

   CVE               DESCRIP
0    1               Hombres
1    2               Mujeres
2    9  Sexo no especificado

In [24]:
#Identificamos la frecuencia de los niveles de la variable
df["v_sexo"].value_counts(1)

1                                       0.469576
2                                       0.380075
1                                       0.085187
2                                       0.064664
9                                       0.000386
9                                       0.000099
Molina Pasquel Y Henriquez              0.000003
MARICELA  LOPEZ CEPEDA\n                0.000003
SFERP S.C.                              0.000003
Sistema Tecnológico de Jalisco, A.C.    0.000003
Name: v_sexo, dtype: float64

In [26]:
#Quitamos las variables que son números
df=df[df["v_sexo"].map(lambda x:str(x).isdigit())]

In [27]:
df.reset_index(drop=True,inplace=True)

In [28]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_sexo,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario
0,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n
1,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.
2,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n
3,4089,30,25405.81,15,1.0,1,1,1,NaN,1,1,11,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO
4,4066,43,60336.83,22,1.0,1,1,1,NaN,1,2,11,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n

In [29]:
sexo.head()["CVE"].index

RangeIndex(start=0, stop=3, step=1)

In [30]:
#Cambiamos el tipo de variable de v_sexo
df["v_sexo"]=df["v_sexo"].astype(int)

In [31]:
df=df.merge(sexo,how="left",right_on="CVE",left_on="v_sexo")

In [32]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_sexo,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,CVE,DESCRIP
0,4093,0,31446.48,6,NaN,1,1,1,NaN,1,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,1,Hombres
1,4092,30,65673.63,16,1.0,1,1,1,NaN,1,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,1,Hombres
2,4040,50,30254.04,6,1.0,1,1,1,NaN,1,2,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,2,Mujeres
3,4089,30,25405.81,15,1.0,1,1,1,NaN,1,1,11,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,1,Hombres
4,4066,43,60336.83,22,1.0,1,1,1,NaN,1,2,11,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,2,Mujeres

In [33]:
#Eliminamos las siguiente columnas
df.drop(columns=["v_sexo","CVE"],inplace=True)

In [34]:
df.columns

Index(['c_edad', 'c_minutos', 'c_monto_de_apoyo', 'c_horas', 'v_ent_regis',
       'v_mun_regis', 'v_ent_resid', 'v_mun_resid', 'v_ent_ocurr',
       'v_mun_ocurr', 'v_ocupacion', 'v_edo_civil', 'v_lugar_ocur',
       'v_sitio_ocur', 'v_nacionalid', 'v_embarazo', 'v_grupo', 'v_lengua',
       'v_clave', 'v_escolarida', 'd_fecha_nac', 'd_fecha_ocurr',
       't_programa_fondo', 't_nombre_del_proyecto',
       't_nombre_del_beneficiario', 'DESCRIP'],
      dtype='object')

In [35]:
#Renombramos la siguiente variables
df.rename(columns={"DESCRIP":"v_sexo"},inplace=True)

In [36]:
edad[edad["CVE"].astype(str).str.startswith("4")]

      CVE                          DESCRIP
67   4001  Un año
68   4002  Dos años
69   4003  Tres años
70   4004  Cuatro años
71   4005  Cinco años
..    ...                              ...
183  4117  Ciento diecisiete años
184  4118  Ciento dieciocho años
185  4119  Ciento diecinueve años
186  4120  Ciento veinte años
187  4998  Edad en años no especificada

[121 rows x 2 columns]

In [37]:
#Cambiamos el tipo de variable a "str"
df["c_monto_de_apoyo"].astype(str).dtype

dtype('O')

In [38]:
#Identificamos los registros que inician con 4
df=df[df["c_edad"].map(lambda x:str(x).startswith("4"))]

In [39]:
df.reset_index(drop=True,inplace=True)

In [40]:
df["c_edad"].dtype

dtype('int64')

In [41]:
edad

      CVE                          DESCRIP
0    1001  Una hora
1    1002  Dos horas
2    1003  Tres horas
3    1004  Cuatro horas
4    1005  Cinco horas
..    ...                              ...
183  4117  Ciento diecisiete años
184  4118  Ciento dieciocho años
185  4119  Ciento diecinueve años
186  4120  Ciento veinte años
187  4998  Edad en años no especificada

[188 rows x 2 columns]

In [42]:
df["c_edad"].astype(str).str[-3:].astype(int)

0         93
1         92
2         40
3         89
4         66
          ..
629267    28
629268    32
629269    43
629270     3
629271     1
Name: c_edad, Length: 629272, dtype: int64

In [43]:

df["c_edad"]=df["c_edad"].astype(str).str[-3:].astype(int)

In [44]:
df["c_edad"].dtype

dtype('int64')

In [45]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,11,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,11,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629267,28,99,148566.0,99,NaN,56,32,56,NaN,56,98,NaN,8,1,1,8,27,NaN,6628,4,1987-06-04,2015-04-13,"Programa de Desarrollo de Prototipos, 2018",Procesamiento de datos de almacén con tecnolog...,Emergys México S.A. de C.V.,Hombres
629268,32,30,491058.0,4,NaN,39,32,39,NaN,39,1,NaN,4,10,1,8,27,2.0,6634,4,1983-04-20,2015-07-17,"Programa de Desarrollo de Prototipos, 2018",Prototipo tecnológico de juguete interactivo p...,"CCLP, S.A. de C.V.",Hombres
629269,43,20,157140.0,0,32.0,56,32,999,NaN,56,11,NaN,88,3,2,3,8,9.0,6683,4,1972-07-01,2015-10-28,"Programa de Desarrollo de Prototipos, 2018",Dispositivo de prototipo de gravedad cero para...,Compañia Power Tools S.A. de C.V.,Mujeres
629270,3,10,149000.0,22,NaN,10,32,49,NaN,10,97,NaN,88,1,1,8,9,9.0,6691,99,2012-11-22,2015-12-08,"Programa de Desarrollo de Prototipos, 2018",Máquina tribológica para medir el desgaste en ...,Universidad de Guadalajara,Mujeres
629271,1,40,150241.0,13,32.0,40,19,6,NaN,7,97,NaN,0,10,1,8,5,NaN,6696,88,2014-10-24,2015-06-04,"Programa de Desarrollo de Prototipos, 2018",Interfaz USB Aislada para Conexión de Instrume...,"Consire, S.A. de C.V.",Mujeres

In [46]:
import numpy as np

In [47]:
#Veamos ahora los la distribución de percentiles
df["c_edad"].describe(percentiles=np.arange(0.1,1.1,.1))

count    629272.000000
mean         70.412760
std          66.978334
min           1.000000
10%          36.000000
20%          50.000000
30%          58.000000
40%          65.000000
50%          70.000000
60%          75.000000
70%          80.000000
80%          84.000000
90%          89.000000
100%        998.000000
max         998.000000
Name: c_edad, dtype: float64

In [49]:
#Escojamos los percentiles a visualizar
df["c_edad"].describe(percentiles=[.95,.96,.97,.98,.99])

count    629272.000000
mean         70.412760
std          66.978334
min           1.000000
50%          70.000000
95%          93.000000
96%          94.000000
97%          95.000000
98%          97.000000
99%         100.000000
max         998.000000
Name: c_edad, dtype: float64

In [50]:
df.shape

(629272, 26)

In [52]:
#Nos quedamos con solo los menores a 97
df[df["c_edad"].map(lambda x:x<97)]

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,11,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,11,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629267,28,99,148566.0,99,NaN,56,32,56,NaN,56,98,NaN,8,1,1,8,27,NaN,6628,4,1987-06-04,2015-04-13,"Programa de Desarrollo de Prototipos, 2018",Procesamiento de datos de almacén con tecnolog...,Emergys México S.A. de C.V.,Hombres
629268,32,30,491058.0,4,NaN,39,32,39,NaN,39,1,NaN,4,10,1,8,27,2.0,6634,4,1983-04-20,2015-07-17,"Programa de Desarrollo de Prototipos, 2018",Prototipo tecnológico de juguete interactivo p...,"CCLP, S.A. de C.V.",Hombres
629269,43,20,157140.0,0,32.0,56,32,999,NaN,56,11,NaN,88,3,2,3,8,9.0,6683,4,1972-07-01,2015-10-28,"Programa de Desarrollo de Prototipos, 2018",Dispositivo de prototipo de gravedad cero para...,Compañia Power Tools S.A. de C.V.,Mujeres
629270,3,10,149000.0,22,NaN,10,32,49,NaN,10,97,NaN,88,1,1,8,9,9.0,6691,99,2012-11-22,2015-12-08,"Programa de Desarrollo de Prototipos, 2018",Máquina tribológica para medir el desgaste en ...,Universidad de Guadalajara,Mujeres
629271,1,40,150241.0,13,32.0,40,19,6,NaN,7,97,NaN,0,10,1,8,5,NaN,6696,88,2014-10-24,2015-06-04,"Programa de Desarrollo de Prototipos, 2018",Interfaz USB Aislada para Conexión de Instrume...,"Consire, S.A. de C.V.",Mujeres

In [53]:
df=df[df["c_edad"].map(lambda x:x<97)]

In [54]:
629272/df.shape[0]

1.0224500572746993

In [55]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_ocupacion,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,6,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,7,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,11,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,11,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,11,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
629267,28,99,148566.0,99,NaN,56,32,56,NaN,56,98,NaN,8,1,1,8,27,NaN,6628,4,1987-06-04,2015-04-13,"Programa de Desarrollo de Prototipos, 2018",Procesamiento de datos de almacén con tecnolog...,Emergys México S.A. de C.V.,Hombres
629268,32,30,491058.0,4,NaN,39,32,39,NaN,39,1,NaN,4,10,1,8,27,2.0,6634,4,1983-04-20,2015-07-17,"Programa de Desarrollo de Prototipos, 2018",Prototipo tecnológico de juguete interactivo p...,"CCLP, S.A. de C.V.",Hombres
629269,43,20,157140.0,0,32.0,56,32,999,NaN,56,11,NaN,88,3,2,3,8,9.0,6683,4,1972-07-01,2015-10-28,"Programa de Desarrollo de Prototipos, 2018",Dispositivo de prototipo de gravedad cero para...,Compañia Power Tools S.A. de C.V.,Mujeres
629270,3,10,149000.0,22,NaN,10,32,49,NaN,10,97,NaN,88,1,1,8,9,9.0,6691,99,2012-11-22,2015-12-08,"Programa de Desarrollo de Prototipos, 2018",Máquina tribológica para medir el desgaste en ...,Universidad de Guadalajara,Mujeres
629271,1,40,150241.0,13,32.0,40,19,6,NaN,7,97,NaN,0,10,1,8,5,NaN,6696,88,2014-10-24,2015-06-04,"Programa de Desarrollo de Prototipos, 2018",Interfaz USB Aislada para Conexión de Instrume...,"Consire, S.A. de C.V.",Mujeres

In [56]:
df.reset_index(drop=True,inplace=True)

In [57]:
#IDENTIFIQUEMOS LA FRECUECIA DE LOS NIVELES DE LA VARIABLE
df["v_ocupacion"].value_counts()

11    340094
6      72707
7      39196
4      32395
2      27211
98     26734
99     24017
9      18429
8      14322
5       9417
97      5020
3       3448
1       2253
10       212
Name: v_ocupacion, dtype: int64

In [58]:
ocupacion

    CVE                                            DESCRIP
0     1                   Funcionarios, directores y jefes
1     2                          Profesionistas y técnicos
2     3  Trabajadores auxiliares en actividades adminis...
3     4  Comerciantes, empleados en ventas y agentes de...
4     5  Trabajadores en servicios personales y vigilancia
5     6  Trabajadores en actividades agrícolas, ganader...
6     7                           Trabajadores artesanales
7     8  Operadores de maquinaria industrial, ensamblad...
8     9  Trabajadores en actividades elementales y de a...
9    10                                      Busca trabajo
10   11                                         No trabaja
11   97                      No aplica a menores de 5 años
12   98        Ocupaciones insuficientemente especificadas
13   99                          Ocupación no especificada

In [59]:
#Lo cruzamos con el catologo
df=df.merge(ocupacion,how="left",right_on="CVE",left_on="v_ocupacion")

In [60]:
#Eliminamos y renombramos columnas
df.drop(columns=["CVE","v_ocupacion"],inplace=True)
df.rename(columns={"DESCRIP":"v_ocupacion"},inplace=True)

In [61]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,v_escolarida,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo,v_ocupacion
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,8,NaN,6344,3,1921-08-25,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres,"Trabajadores en actividades agrícolas, ganader..."
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,8,2,NaN,6345,3,1922-06-12,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres,Trabajadores artesanales
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,5,7,NaN,6364,4,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres,No trabaja
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,NaN,88,11,1,8,5,9.0,6367,1,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres,No trabaja
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,8,6,NaN,6368,3,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres,No trabaja
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615450,28,99,148566.0,99,NaN,56,32,56,NaN,56,NaN,8,1,1,8,27,NaN,6628,4,1987-06-04,2015-04-13,"Programa de Desarrollo de Prototipos, 2018",Procesamiento de datos de almacén con tecnolog...,Emergys México S.A. de C.V.,Hombres,Ocupaciones insuficientemente especificadas
615451,32,30,491058.0,4,NaN,39,32,39,NaN,39,NaN,4,10,1,8,27,2.0,6634,4,1983-04-20,2015-07-17,"Programa de Desarrollo de Prototipos, 2018",Prototipo tecnológico de juguete interactivo p...,"CCLP, S.A. de C.V.",Hombres,"Funcionarios, directores y jefes"
615452,43,20,157140.0,0,32.0,56,32,999,NaN,56,NaN,88,3,2,3,8,9.0,6683,4,1972-07-01,2015-10-28,"Programa de Desarrollo de Prototipos, 2018",Dispositivo de prototipo de gravedad cero para...,Compañia Power Tools S.A. de C.V.,Mujeres,No trabaja
615453,3,10,149000.0,22,NaN,10,32,49,NaN,10,NaN,88,1,1,8,9,9.0,6691,99,2012-11-22,2015-12-08,"Programa de Desarrollo de Prototipos, 2018",Máquina tribológica para medir el desgaste en ...,Universidad de Guadalajara,Mujeres,No aplica a menores de 5 años
615454,1,40,150241.0,13,32.0,40,19,6,NaN,7,NaN,0,10,1,8,5,NaN,6696,88,2014-10-24,2015-06-04,"Programa de Desarrollo de Prototipos, 2018",Interfaz USB Aislada para Conexión de Instrume...,"Consire, S.A. de C.V.",Mujeres,No aplica a menores de 5 años

In [62]:
#Unimos esolaridad co v_escolaridad
df=df.merge(escolaridad,how="left",left_on="v_escolarida",right_on="CVE")
#Eliminamos columnas
df.drop(columns=["CVE","v_escolarida"],inplace=True)
#Renombramos columnas
df.rename(columns={"DESCRIP":"v_escolarida"},inplace=True)

In [63]:
df["d_fecha_ocurr"].dtype

dtype('O')

In [64]:
df["d_fecha_ocurr"]=pd.to_datetime(df["d_fecha_ocurr"])

In [65]:
#Creamos 2 variables
df["v_fecha_ocurr_mes"]=df["d_fecha_ocurr"].map(lambda x:x.month)
df["v_fecha_ocurr_dia"]=df["d_fecha_ocurr"].map(lambda x:x.day)

In [66]:
list(df.filter(like="c_").columns)

['c_edad', 'c_minutos', 'c_monto_de_apoyo', 'c_horas']

In [67]:
#Cambiamos el tipo de variable
df["c_minutos"]=df["c_minutos"].astype(int)
df["c_monto_de_apoyo"]=df["c_monto_de_apoyo"].astype(float)
df["c_horas"]=df["c_horas"].astype(int)

In [68]:
# Porcentaje de frecuencia de escolaridad
df["v_escolarida"].value_counts(1)

Primaria incompleta                       0.278862
Sin escolaridad                           0.203048
Primaria completa                         0.195988
Secundaria completa                       0.098244
Profesional                               0.068861
Bachillerato o Preparatoria completo      0.054995
No especificado                           0.041170
Secundaria incompleta                     0.027714
Bachillerato o Preparatoria incompleto    0.019527
No aplica a menores de 3 años             0.005747
Posgrado                                  0.004070
Preescolar                                0.001773
Name: v_escolarida, dtype: float64

In [70]:
pip install unidecode

Collecting unidecode
  Downloading https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl (238kB)
     |████████████████████████████████| 245kB 2.8MB/s
Installing collected packages: unidecode
Successfully installed unidecode-1.1.1

In [71]:
from unidecode import unidecode

In [72]:
#Pasamos a minusculas el texto
df["v_escolarida"]=df["v_escolarida"].map(lambda x:unidecode(x.lower()))

In [73]:
#Frecuencia de niveles
df["v_escolarida"].value_counts(1)

primaria incompleta                       0.278862
sin escolaridad                           0.203048
primaria completa                         0.195988
secundaria completa                       0.098244
profesional                               0.068861
bachillerato o preparatoria completo      0.054995
no especificado                           0.041170
secundaria incompleta                     0.027714
bachillerato o preparatoria incompleto    0.019527
no aplica a menores de 3 anos             0.005747
posgrado                                  0.004070
preescolar                                0.001773
Name: v_escolarida, dtype: float64

In [74]:
#Diccionario para renombrar
dictio={"primaria completa":"primaria completa","primaria  completa ":"primaria completa"}

In [75]:
#quitamos espacios
"primaria  completa ".strip()

'primaria  completa'

In [76]:
" primaria  completa".lstrip()

'primaria  completa'

In [77]:
df["v_escolarida"]=df["v_escolarida"].map(lambda x:x.strip())
df["v_escolarida"]=df["v_escolarida"].map(lambda x:x.lstrip())

In [85]:
dictio=dict(zip(list(df["v_escolarida"].value_counts(1).index)[-2:],["otros"]*2))

In [86]:
lista=list(df["v_escolarida"].value_counts(1).index)

In [87]:
a=list(df["v_escolarida"].value_counts(1).index)[-2:]

In [88]:
a

['posgrado', 'preescolar']

In [89]:
b=["otros"]*2

In [90]:
b

['otros', 'otros']

In [91]:
a

['posgrado', 'preescolar']

In [92]:
dict(zip(a,b))

{'posgrado': 'otros', 'preescolar': 'otros'}

In [93]:
type(df["v_escolarida"].value_counts(1))

pandas.core.series.Series

In [95]:
#Frecuencia de niveles
pd.DataFrame(df["v_escolarida"].value_counts(1)).reset_index()

                                     index  v_escolarida
0                      primaria incompleta      0.278862
1                          sin escolaridad      0.203048
2                        primaria completa      0.195988
3                      secundaria completa      0.098244
4                              profesional      0.068861
5     bachillerato o preparatoria completo      0.054995
6                          no especificado      0.041170
7                    secundaria incompleta      0.027714
8   bachillerato o preparatoria incompleto      0.019527
9            no aplica a menores de 3 anos      0.005747
10                                posgrado      0.004070
11                              preescolar      0.001773

In [96]:
#reemplazamos
df["v_escolarida"]=df["v_escolarida"].replace(dictio)

In [97]:
df["d_fecha_nac"].iloc[[0,1]]=["1","11"]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [98]:
df["d_fecha_nac"].iloc[[0,1]]=["1","22"]

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [99]:
df.head()

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo,v_ocupacion,v_escolarida,v_fecha_ocurr_mes,v_fecha_ocurr_dia
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,8,NaN,6344,1,2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres,"Trabajadores en actividades agrícolas, ganader...",primaria incompleta,9,26
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,8,2,NaN,6345,22,2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres,Trabajadores artesanales,primaria incompleta,12,14
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,5,7,NaN,6364,1974-12-17,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres,No trabaja,primaria completa,7,16
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,NaN,88,11,1,8,5,9.0,6367,1926-05-04,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres,No trabaja,sin escolaridad,12,26
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,8,6,NaN,6368,1949-08-25,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres,No trabaja,primaria incompleta,2,10

In [100]:
df["d_fecha_nac"]=pd.to_datetime(df["d_fecha_nac"],errors="coerce",dayfirst=True)

In [101]:
df["d_fecha_nac"].dropna()

2        1974-12-17
3        1926-05-04
4        1949-08-25
5        1948-05-29
6        1971-08-20
            ...
615450   1987-06-04
615451   1983-04-20
615452   1972-07-01
615453   2012-11-22
615454   2014-10-24
Name: d_fecha_nac, Length: 608258, dtype: datetime64[ns]

In [102]:
df["d_fecha_nac"]=df["d_fecha_nac"].fillna("[2,4]")

In [103]:
from datetime import datetime

In [104]:
a="2016--12//12"

In [105]:
datetime.strptime(a,"%Y--%m//%d")

datetime.datetime(2016, 12, 12, 0, 0)

In [106]:
df

,c_edad,c_minutos,c_monto_de_apoyo,c_horas,v_ent_regis,v_mun_regis,v_ent_resid,v_mun_resid,v_ent_ocurr,v_mun_ocurr,v_edo_civil,v_lugar_ocur,v_sitio_ocur,v_nacionalid,v_embarazo,v_grupo,v_lengua,v_clave,d_fecha_nac,d_fecha_ocurr,t_programa_fondo,t_nombre_del_proyecto,t_nombre_del_beneficiario,v_sexo,v_ocupacion,v_escolarida,v_fecha_ocurr_mes,v_fecha_ocurr_dia
0,93,0,31446.48,6,NaN,1,1,1,NaN,1,NaN,88,11,1,8,8,NaN,6344,"[2,4]",2015-09-26,Programa Jalisciense de Fomento a la Propieda...,PCT - SISTEMA MECATRÓNICO PARA EL CONTROL DE I...,RICARDO MERCADO CORTÉS\n,Hombres,"Trabajadores en actividades agrícolas, ganader...",primaria incompleta,9,26
1,92,30,65673.63,16,1.0,1,1,1,NaN,1,NaN,88,11,1,8,2,NaN,6345,"[2,4]",2015-12-14,Programa Jalisciense de Fomento a la Propieda...,MX-EMPAQUE CÓNICO PARA LA CONEXIÓN \nDE MANGUE...,CORPORATIVO BORO S.A. DE C.V.,Hombres,Trabajadores artesanales,primaria incompleta,12,14
2,40,50,30254.04,6,1.0,1,1,1,NaN,1,NaN,88,1,1,5,7,NaN,6364,1974-12-17 00:00:00,2015-07-16,Programa Jalisciense de Fomento a la Propieda...,DISPOSITIVO PERSONAL DE COMUNICACIÓN REMOTA PA...,GERALDINA VEGA GAMBOA\n,Mujeres,No trabaja,primaria completa,7,16
3,89,30,25405.81,15,1.0,1,1,1,NaN,1,NaN,88,11,1,8,5,9.0,6367,1926-05-04 00:00:00,2015-12-26,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA DIFERENCIAL QUE CONTROLA LA TRACCIÓ...,SERVANDO SOTO VELASCO,Hombres,No trabaja,sin escolaridad,12,26
4,66,43,60336.83,22,1.0,1,1,1,NaN,1,NaN,88,3,1,8,6,NaN,6368,1949-08-25 00:00:00,2015-02-10,Programa Jalisciense de Fomento a la Propieda...,MX-SISTEMA ACOPLADOR AUTOMATIZADO PARA MÁQUIN...,SERVANDO SOTO VELASCO\n,Mujeres,No trabaja,primaria incompleta,2,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615450,28,99,148566.00,99,NaN,56,32,56,NaN,56,NaN,8,1,1,8,27,NaN,6628,1987-06-04 00:00:00,2015-04-13,"Programa de Desarrollo de Prototipos, 2018",Procesamiento de datos de almacén con tecnolog...,Emergys México S.A. de C.V.,Hombres,Ocupaciones insuficientemente especificadas,primaria completa,4,13
615451,32,30,491058.00,4,NaN,39,32,39,NaN,39,NaN,4,10,1,8,27,2.0,6634,1983-04-20 00:00:00,2015-07-17,"Programa de Desarrollo de Prototipos, 2018",Prototipo tecnológico de juguete interactivo p...,"CCLP, S.A. de C.V.",Hombres,"Funcionarios, directores y jefes",primaria completa,7,17
615452,43,20,157140.00,0,32.0,56,32,999,NaN,56,NaN,88,3,2,3,8,9.0,6683,1972-07-01 00:00:00,2015-10-28,"Programa de Desarrollo de Prototipos, 2018",Dispositivo de prototipo de gravedad cero para...,Compañia Power Tools S.A. de C.V.,Mujeres,No trabaja,primaria completa,10,28
615453,3,10,149000.00,22,NaN,10,32,49,NaN,10,NaN,88,1,1,8,9,9.0,6691,2012-11-22 00:00:00,2015-12-08,"Programa de Desarrollo de Prototipos, 2018",Máquina tribológica para medir el desgaste en ...,Universidad de Guadalajara,Mujeres,No aplica a menores de 5 años,no especificado,12,8
615454,1,40,150241.00,13,32.0,40,19,6,NaN,7,NaN,0,10,1,8,5,NaN,6696,2014-10-24 00:00:00,2015-06-04,"Programa de Desarrollo de Prototipos, 2018",Interfaz USB Aislada para Conexión de Instrume...,"Consire, S.A. de C.V.",Mujeres,No aplica a menores de 5 años,no aplica a menores de 3 anos,6,4

In [107]:
#seleccionamos 3 variables y agrupamos 2 para traer ESTADISTICOS
df[["c_edad","v_escolarida","v_sexo"]].groupby(["v_escolarida","v_sexo"]).agg(["mean","min","max","count"])

                                                                c_edad      \
                                                                  mean min
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres               52.104316  17
                                       Mujeres               58.911955  17
bachillerato o preparatoria incompleto Hombres               43.803466  15
                                       Mujeres               45.781515  15
no aplica a menores de 3 anos          Hombres                1.369318   1
                                       Mujeres                1.336040   1
no especificado                        Hombres               57.621041   3
                                       Mujeres               66.928786   3
                                       Sexo no especificado  45.272727  20
otros                                  Hombres               55.052049   3
                                       Mujeres               45.384948   3
primaria completa                      Hombres               62.775054  11
                                       Mujeres               68.858812  11
primaria incompleta                    Hombres               70.147353   6
                                       Mujeres               73.092210   6
                                       Sexo no especificado  94.000000  94
profesional                            Hombres               60.985245  18
                                       Mujeres               62.135107  18
                                       Sexo no especificado  92.000000  92
secundaria completa                    Hombres               50.069730  14
                                       Mujeres               57.312762  14
secundaria incompleta                  Hombres               46.911189  12
                                       Mujeres               51.071824  12
sin escolaridad                        Hombres               73.117685   3
                                       Mujeres               76.467385   3
                                       Sexo no especificado  60.000000  60


                                                            max  count
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres               96  20831
                                       Mujeres               96  13016
bachillerato o preparatoria incompleto Hombres               96   8599
                                       Mujeres               96   3419
no aplica a menores de 3 anos          Hombres                2   1936
                                       Mujeres                2   1601
no especificado                        Hombres               96  15978
                                       Mujeres               96   9338
                                       Sexo no especificado  80     22
otros                                  Hombres               96   2440
                                       Mujeres               96   1156
primaria completa                      Hombres               96  66616
                                       Mujeres               96  54006
primaria incompleta                    Hombres               96  93001
                                       Mujeres               96  78625
                                       Sexo no especificado  94      1
profesional                            Hombres               96  28058
                                       Mujeres               96  14322
                                       Sexo no especificado  92      1
secundaria completa                    Hombres               96  38477
                                       Mujeres               96  21988
secundaria incompleta                  Hombres               96  12003
                                       Mujeres               96   5054
sin escolaridad                        Hombres               96  54476
                                       Mujeres               96  70490
                                       Sexo no especificado  60      1

In [112]:
#Seleccionamos 3 variables, agrupamos 2 y sacamos estadisticos de 2 variables
exa=df[["c_edad","v_escolarida","v_sexo","v_clave"]].groupby(["v_escolarida","v_sexo"]).agg({"c_edad":["mean","min"],"v_clave":["max","count"]})

In [113]:
exa

                                                                c_edad      \
                                                                  mean min
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres               52.104316  17
                                       Mujeres               58.911955  17
bachillerato o preparatoria incompleto Hombres               43.803466  15
                                       Mujeres               45.781515  15
no aplica a menores de 3 anos          Hombres                1.369318   1
                                       Mujeres                1.336040   1
no especificado                        Hombres               57.621041   3
                                       Mujeres               66.928786   3
                                       Sexo no especificado  45.272727  20
otros                                  Hombres               55.052049   3
                                       Mujeres               45.384948   3
primaria completa                      Hombres               62.775054  11
                                       Mujeres               68.858812  11
primaria incompleta                    Hombres               70.147353   6
                                       Mujeres               73.092210   6
                                       Sexo no especificado  94.000000  94
profesional                            Hombres               60.985245  18
                                       Mujeres               62.135107  18
                                       Sexo no especificado  92.000000  92
secundaria completa                    Hombres               50.069730  14
                                       Mujeres               57.312762  14
secundaria incompleta                  Hombres               46.911189  12
                                       Mujeres               51.071824  12
sin escolaridad                        Hombres               73.117685   3
                                       Mujeres               76.467385   3
                                       Sexo no especificado  60.000000  60

                                                            v_clave
                                                                max  count
v_escolarida                           v_sexo
bachillerato o preparatoria completo   Hombres                 6897  20831
                                       Mujeres                 6897  13016
bachillerato o preparatoria incompleto Hombres                 6897   8599
                                       Mujeres                 6897   3419
no aplica a menores de 3 anos          Hombres                 6897   1936
                                       Mujeres                 6897   1601
no especificado                        Hombres                 6897  15978
                                       Mujeres                 6897   9338
                                       Sexo no especificado    6836     22
otros                                  Hombres                 6897   2440
                                       Mujeres                 6897   1156
primaria completa                      Hombres                 6897  66616
                                       Mujeres                 6897  54006
primaria incompleta                    Hombres                 6897  93001
                                       Mujeres                 6897  78625
                                       Sexo no especificado    6724      1
profesional                            Hombres                 6897  28058
                                       Mujeres                 6897  14322
                                       Sexo no especificado    6544      1
secundaria completa                    Hombres                 6897  38477
                                       Mujeres                 6897  21988
secundaria incompleta                  Hombres                 6897  12003
                                       Mujeres                 6897   5054
sin escolaridad                        Hombres                 6897  54476
                                       Mujeres                 6897  70490
                                       Sexo no especificado    6579      1

In [114]:
exa["c_edad"]["mean"].values

array([52.10431568, 58.91195452, 43.80346552, 45.78151506,  1.36931818,
        1.33603998, 57.62104143, 66.92878561, 45.27272727, 55.05204918,
       45.3849481 , 62.77505404, 68.85881198, 70.14735325, 73.09220986,
       94.        , 60.98524485, 62.13510683, 92.        , 50.06972997,
       57.31276151, 46.91118887, 51.0718243 , 73.11768485, 76.46738544,
       60.        ])

In [115]:
list(df.columns)

['c_edad',
 'c_minutos',
 'c_monto_de_apoyo',
 'c_horas',
 'v_ent_regis',
 'v_mun_regis',
 'v_ent_resid',
 'v_mun_resid',
 'v_ent_ocurr',
 'v_mun_ocurr',
 'v_edo_civil',
 'v_lugar_ocur',
 'v_sitio_ocur',
 'v_nacionalid',
 'v_embarazo',
 'v_grupo',
 'v_lengua',
 'v_clave',
 'd_fecha_nac',
 'd_fecha_ocurr',
 't_programa_fondo',
 't_nombre_del_proyecto',
 't_nombre_del_beneficiario',
 'v_sexo',
 'v_ocupacion',
 'v_escolarida',
 'v_fecha_ocurr_mes',
 'v_fecha_ocurr_dia']

In [116]:
pd.set_option("display.max_columns",1000)
pd.set_option("display.max_rows",1000)

In [117]:
for i in df.columns:
    print(i)

c_edad
c_minutos
c_monto_de_apoyo
c_horas
v_ent_regis
v_mun_regis
v_ent_resid
v_mun_resid
v_ent_ocurr
v_mun_ocurr
v_edo_civil
v_lugar_ocur
v_sitio_ocur
v_nacionalid
v_embarazo
v_grupo
v_lengua
v_clave
d_fecha_nac
d_fecha_ocurr
t_programa_fondo
t_nombre_del_proyecto
t_nombre_del_beneficiario
v_sexo
v_ocupacion
v_escolarida
v_fecha_ocurr_mes
v_fecha_ocurr_dia