<a href="https://colab.research.google.com/github/virf96/Basico/blob/main/Copia_de_Ingenier%C3%ADa_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
df.to_csv("/home/carlita/Documents/Diplomado/Datos/feat_ing.csv",index=False)

In [ ]:
df.duplicated().sum()

0

In [ ]:
df=df.rename(columns={"c_feat_59":"temperatura"})

In [ ]:
df["date"].diff().describe()

count                         2079
mean     1 days 00:18:08.167388167
std      0 days 00:08:18.759634616
min                1 days 00:04:00
25%                1 days 00:11:00
50%                1 days 00:18:00
75%                1 days 00:25:00
max                1 days 00:32:00
Name: date, dtype: object

In [ ]:
df.drop(columns=["c_feat_60"],inplace=True)

In [ ]:
df["temperatura"].shift(-1)

0      0.0044
1      0.0078
2      0.0117
3      0.0094
4      0.0062
        ...
203    0.0067
204    0.0031
205    0.0048
206    0.0115
207       NaN
Name: temperatura, Length: 2080, dtype: float64

In [ ]:
df["temperatura"]

0      0.0032
1      0.0044
2      0.0078
3      0.0117
4      0.0094
        ...
203    0.0157
204    0.0067
205    0.0031
206    0.0048
207    0.0115
Name: temperatura, Length: 2080, dtype: float64

In [ ]:
df["temperatura"].shift(2)

0         NaN
1         NaN
2      0.0032
3      0.0044
4      0.0078
        ...
203    0.0031
204    0.0103
205    0.0157
206    0.0067
207    0.0031
Name: temperatura, Length: 2080, dtype: float64

## Desfase de tu objetivo (Predecir la temperatura del día siguiente)

In [ ]:
## Información anterior

In [ ]:
df["temperatura"]=df["temperatura"].shift(-1)

In [ ]:
df["c_feat_0"].diff(1)

0         NaN
1      0.0253
2     -0.0191
3     -0.0162
4      0.0662
        ...
203   -0.0085
204    0.0136
205    0.0199
206   -0.0219
207   -0.0043
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
df["c_feat_0"].diff(2)

0         NaN
1         NaN
2      0.0062
3     -0.0353
4      0.0500
        ...
203   -0.0148
204    0.0051
205    0.0335
206   -0.0020
207   -0.0262
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
0.0262-0.0200

0.006200000000000001

In [ ]:
df["c_feat_0"]

0      0.0200
1      0.0453
2      0.0262
3      0.0100
4      0.0762
        ...
203    0.0187
204    0.0323
205    0.0522
206    0.0303
207    0.0260
Name: c_feat_0, Length: 2080, dtype: float64

## Ventanas de tiempo

In [ ]:
df["c_feat_0"].rolling(3).mean()

0           NaN
1           NaN
2      0.030500
3      0.027167
4      0.037467
         ...
203    0.026467
204    0.026067
205    0.034400
206    0.038267
207    0.036167
Name: c_feat_0, Length: 2080, dtype: float64

## Información del día anterior

In [ ]:
df["c_feat_0"].shift(1)

0         NaN
1      0.0200
2      0.0453
3      0.0262
4      0.0100
        ...
203    0.0272
204    0.0187
205    0.0323
206    0.0522
207    0.0303
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
df["c_feat_0"]

0      0.0200
1      0.0453
2      0.0262
3      0.0100
4      0.0762
        ...
203    0.0187
204    0.0323
205    0.0522
206    0.0303
207    0.0260
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
df["c_feat_0"].pct_change(1)

0           NaN
1      1.265000
2     -0.421634
3     -0.618321
4      6.620000
         ...
203   -0.312500
204    0.727273
205    0.616099
206   -0.419540
207   -0.141914
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
df["c_feat_0"].pct_change(-1)

0     -0.558499
1      0.729008
2      1.620000
3     -0.868766
4      1.664336
         ...
203   -0.421053
204   -0.381226
205    0.722772
206    0.165385
207         NaN
Name: c_feat_0, Length: 2080, dtype: float64

In [ ]:
(0.0453-0.0200)/0.0200

1.265

In [ ]:
(0.0200-0.0453)/0.0453

-0.5584988962472406

In [ ]:
variables=(df.filter(like="c_").columns)

In [ ]:
df[]

In [ ]:
df[f"c_feat_0_diff_1"]=df["c_feat_0"].diff(1)

In [ ]:
#ventanas de tiempo de dos periodos
df[f"c_feat_0_roll_mean"] = df["c_feat_0"].rolling(2).mean()
#información del día anterior
df[f"c_feat_0_shift_1"] = df["c_feat_0"].shift(1)
#porcentaje de cambio
df[f"c_feat_0_pct_1"]= df["c_feat_0"].pct_change(1)

In [ ]:
df

,date,c_feat_0,c_feat_1,c_feat_2,c_feat_3,c_feat_4,c_feat_5,c_feat_6,c_feat_7,c_feat_8,...,c_feat_53,c_feat_54,c_feat_55,c_feat_56,c_feat_57,c_feat_58,temperatura,c_feat_0_roll_mean,c_feat_0_shift_1,c_feat_0_pct_1
0,2010-12-01 00:00:00,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,...,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0044,0.0200,NaN,NaN
1,2010-12-02 00:26:00,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,...,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0078,0.0453,0.0200,1.265000
2,2010-12-03 00:31:00,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,...,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0117,0.0262,0.0453,-0.421634
3,2010-12-04 00:40:00,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,...,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0094,0.0100,0.0262,-0.618321
4,2010-12-05 00:58:00,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,...,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0062,0.0762,0.0100,6.620000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,2016-08-31 19:21:00,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,...,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0067,0.0187,0.0272,-0.312500
204,2016-09-01 19:32:00,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,...,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0031,0.0323,0.0187,0.727273
205,2016-09-02 19:41:00,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,...,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0048,0.0522,0.0323,0.616099
206,2016-09-03 19:53:00,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,...,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0115,0.0303,0.0522,-0.419540
207,2016-09-04 20:12:00,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,...,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,NaN,0.0260,0.0303,-0.141914

In [ ]:
for col in variables:
    for i in range(12):
        df[f"{col}_diff_{i+1}"] = df[f"{col}"].diff(i+1)
        df[f"{col}_ma_{i+1}"] = df[f"{col}"].rolling(i+1).mean()
        df[f"{col}_t-{i+1}"] = df[f"{col}"].shift(i+1)
        df[f"{col}_pct_{i+1}"] = df[f"{col}"].pct_change(i+1)

In [ ]:
df

,date,c_feat_0,c_feat_1,c_feat_2,c_feat_3,c_feat_4,c_feat_5,c_feat_6,c_feat_7,c_feat_8,...,c_feat_58_t-10,c_feat_58_pct_10,c_feat_58_diff_11,c_feat_58_ma_11,c_feat_58_t-11,c_feat_58_pct_11,c_feat_58_diff_12,c_feat_58_ma_12,c_feat_58_t-12,c_feat_58_pct_12
0,2010-12-01 00:00:00,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-12-02 00:26:00,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-12-03 00:31:00,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-12-04 00:40:00,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-12-05 00:58:00,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,2016-08-31 19:21:00,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,...,0.0013,13.846154,0.0159,0.004300,0.0034,4.676471,0.0192,0.004225,0.0001,192.000000
204,2016-09-01 19:32:00,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,...,0.0022,1.818182,0.0049,0.004745,0.0013,3.769231,0.0028,0.004458,0.0034,0.823529
205,2016-09-02 19:41:00,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,...,0.0024,2.208333,0.0055,0.005245,0.0022,2.500000,0.0064,0.004992,0.0013,4.923077
206,2016-09-03 19:53:00,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,...,0.0017,1.117647,0.0012,0.005355,0.0024,0.500000,0.0014,0.005108,0.0022,0.636364
207,2016-09-04 20:12:00,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,...,0.0027,1.259259,0.0044,0.005755,0.0017,2.588235,0.0037,0.005417,0.0024,1.541667

In [ ]:
df.shape

(2080, 2895)

In [ ]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
poly = PolynomialFeatures(2)

In [ ]:
va

In [ ]:
df_pol = poly.fit_transform(df[variables])

In [ ]:
df_pol = pd.DataFrame(columns=poly.get_feature_names(), data=df_pol)

In [ ]:
len(variables)

59

In [ ]:
df_pol

,1,x0,x1,x2,x3,x4,x5,x6,x7,x8,...,x55^2,x55 x56,x55 x57,x55 x58,x56^2,x56 x57,x56 x58,x57^2,x57 x58,x58^2
0,1.0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,...,0.000279,0.000301,0.000140,0.000150,0.000324,0.000151,0.000162,0.000071,0.000076,0.000081
1,1.0,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,...,0.000365,0.000267,0.000094,0.000099,0.000196,0.000069,0.000073,0.000024,0.000025,0.000027
2,1.0,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,...,0.000595,0.000771,0.000400,0.000232,0.000999,0.000518,0.000300,0.000269,0.000156,0.000090
3,1.0,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,...,0.000053,0.000036,0.000032,0.000029,0.000025,0.000022,0.000020,0.000019,0.000018,0.000016
4,1.0,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,...,0.000002,0.000011,0.000007,0.000016,0.000052,0.000035,0.000077,0.000023,0.000051,0.000114
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2075,1.0,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,...,0.000102,0.000066,0.000116,0.000195,0.000042,0.000075,0.000125,0.000132,0.000222,0.000372
2076,1.0,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,...,0.000040,0.000021,0.000020,0.000039,0.000012,0.000011,0.000021,0.000010,0.000020,0.000038
2077,1.0,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,...,0.000079,0.000125,0.000123,0.000069,0.000196,0.000193,0.000108,0.000190,0.000106,0.000059
2078,1.0,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,...,0.000012,0.000012,0.000028,0.000013,0.000012,0.000027,0.000012,0.000062,0.000028,0.000013
2079,1.0,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,...,0.000037,0.000024,0.000022,0.000037,0.000016,0.000014,0.000024,0.000013,0.000022,0.000037

## Agrupación de datos

In [ ]:
from scipy.stats import kurtosis 
from scipy.stats import skew

In [ ]:
variables

Index(['c_feat_0', 'c_feat_1', 'c_feat_2', 'c_feat_3', 'c_feat_4', 'c_feat_5',
       'c_feat_6', 'c_feat_7', 'c_feat_8', 'c_feat_9', 'c_feat_10',
       'c_feat_11', 'c_feat_12', 'c_feat_13', 'c_feat_14', 'c_feat_15',
       'c_feat_16', 'c_feat_17', 'c_feat_18', 'c_feat_19', 'c_feat_20',
       'c_feat_21', 'c_feat_22', 'c_feat_23', 'c_feat_24', 'c_feat_25',
       'c_feat_26', 'c_feat_27', 'c_feat_28', 'c_feat_29', 'c_feat_30',
       'c_feat_31', 'c_feat_32', 'c_feat_33', 'c_feat_34', 'c_feat_35',
       'c_feat_36', 'c_feat_37', 'c_feat_38', 'c_feat_39', 'c_feat_40',
       'c_feat_41', 'c_feat_42', 'c_feat_43', 'c_feat_44', 'c_feat_45',
       'c_feat_46', 'c_feat_47', 'c_feat_48', 'c_feat_49', 'c_feat_50',
       'c_feat_51', 'c_feat_52', 'c_feat_53', 'c_feat_54', 'c_feat_55',
       'c_feat_56', 'c_feat_57', 'c_feat_58', 'c_feat_59', 'c_feat_60'],
      dtype='object')

In [ ]:
variables=list(variables)[:50]

In [ ]:
df.groupby(['Location', pd.Grouper(freq='H')])['Event'].count()

In [ ]:
df=df.set_index("date")

In [ ]:
df[:10].resample('1D').agg(lambda x:x*2)

,c_feat_0,c_feat_1,c_feat_2,c_feat_3,c_feat_4,c_feat_5,c_feat_6,c_feat_7,c_feat_8,c_feat_9,...,c_feat_50,c_feat_51,c_feat_52,c_feat_53,c_feat_54,c_feat_55,c_feat_56,c_feat_57,c_feat_58,temperatura
date,,,,,,,,,,,,,,,,,,,,,
2010-12-01,0.0400,0.0742,0.0856,0.0414,0.1908,0.1972,0.3078,0.3202,0.6218,0.4222,...,0.0464,0.0054,0.0130,0.0318,0.0144,0.0334,0.0360,0.0168,0.0180,0.0088
2010-12-02,0.0906,0.1046,0.1686,0.1378,0.2366,0.5166,0.4312,0.6962,0.6674,0.5744,...,0.0250,0.0168,0.0178,0.0096,0.0188,0.0382,0.0280,0.0098,0.0104,0.0156
2010-12-03,0.0524,0.1164,0.2198,0.2166,0.1948,0.4560,0.4862,0.7542,1.1196,1.2388,...,0.0066,0.0464,0.0332,0.0190,0.0360,0.0488,0.0632,0.0328,0.0190,0.0234
2010-12-04,0.0200,0.0342,0.1246,0.0410,0.0410,0.0736,0.2196,0.2552,0.1196,0.2528,...,0.0482,0.0242,0.0072,0.0300,0.0170,0.0146,0.0100,0.0088,0.0080,0.0188
2010-12-05,0.1524,0.1332,0.0962,0.0788,0.1180,0.1298,0.2418,0.4934,0.7128,0.8918,...,0.0312,0.0062,0.0108,0.0210,0.0220,0.0030,0.0144,0.0096,0.0214,0.0124
2010-12-06,0.0572,0.0906,0.0554,0.0348,0.0768,0.1980,0.2402,0.3666,0.4210,0.6078,...,0.0208,0.0090,0.0028,0.0076,0.0026,0.0178,0.0114,0.0054,0.0102,0.0206
2010-12-07,0.0634,0.1912,0.2642,0.2816,0.3348,0.3420,0.1462,0.2802,0.4166,0.7026,...,0.0390,0.0402,0.0496,0.0262,0.0140,0.0276,0.0184,0.0286,0.0072,0.0106
2010-12-08,0.1038,0.1096,0.1684,0.0638,0.2316,0.1844,0.2054,0.1226,0.2930,0.5676,...,0.0104,0.0162,0.0240,0.0090,0.0242,0.0194,0.0170,0.0094,0.0096,0.0044
2010-12-09,0.0446,0.0750,0.0968,0.0950,0.1294,0.1182,0.1506,0.0196,0.1368,0.2974,...,0.0122,0.0290,0.0256,0.0290,0.0116,0.0098,0.0130,0.0186,0.0118,0.0080
2010-12-10,0.0328,0.0346,0.0694,0.0140,0.0374,0.1342,0.2112,0.1394,0.1924,0.0502,...,0.0236,0.0180,0.0446,0.0358,0.0168,0.0136,0.0064,0.0070,0.0112,0.0072

In [ ]:
df.resample('1M').agg(lambda x:kurtosis(x))

,c_feat_0,c_feat_1,c_feat_2,c_feat_3,c_feat_4,c_feat_5,c_feat_6,c_feat_7,c_feat_8,c_feat_9,...,c_feat_50,c_feat_51,c_feat_52,c_feat_53,c_feat_54,c_feat_55,c_feat_56,c_feat_57,c_feat_58,temperatura
date,,,,,,,,,,,,,,,,,,,,,
2010-12-31,1.577279,-0.364240,0.335871,1.085080,1.123789,0.111998,-0.075737,0.635351,1.185098,1.027135,...,1.577051,1.502424,-0.261517,-0.655341,-0.044323,0.289299,3.129351,-0.601874,1.095870,-0.240792
2011-01-31,-0.597646,-0.000249,-0.329638,0.195361,1.469254,0.641095,0.603684,0.510165,-0.585810,0.520640,...,-0.080705,3.104457,-0.152475,1.261420,-0.001845,1.121652,1.083286,-0.151008,6.121557,0.077623
2011-02-28,6.074837,14.404978,6.013429,6.171208,1.617851,-0.698531,-0.691690,2.309570,0.220059,1.089997,...,-0.166695,-0.826974,-0.386558,-0.286219,0.026854,2.158216,5.304972,2.889498,5.936736,2.505562
2011-03-31,6.879383,8.569782,6.789442,8.724158,3.483594,2.448794,1.812207,1.534419,0.602421,0.218203,...,-1.079789,-0.387817,-0.953308,-1.091556,-0.551651,0.714429,-0.191028,3.890528,1.922426,8.585580
2011-04-30,-0.626398,-0.589480,-0.714341,-1.008751,0.358484,0.376010,-0.339004,-0.258617,0.012911,-0.693089,...,5.672455,1.043647,0.209817,-1.327940,0.656636,2.370464,3.025069,3.538195,1.302742,-0.102901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-05-31,4.915114,5.424679,5.253140,7.895188,2.942587,4.070309,1.470315,0.283699,-0.515205,-0.397825,...,-0.899907,-0.117424,-1.108456,-0.964621,-0.571079,1.286437,-0.272214,3.976306,1.605803,9.882727
2016-06-30,-0.152013,-1.186992,0.087020,-0.574201,-0.402883,0.693928,-0.124470,-0.112796,-0.176864,-0.600413,...,8.593625,0.263397,3.624400,-1.304544,1.648414,1.273016,-0.601236,-0.303209,-0.122806,-0.493097
2016-07-31,2.007774,3.335997,0.581672,0.426164,5.938600,0.788569,-0.850833,0.913375,2.827685,3.419673,...,10.888950,4.823950,1.527190,1.310832,4.011786,10.403409,7.214033,10.349662,4.078371,-0.230237
2016-08-31,0.611854,0.932582,0.091877,-0.752976,-0.743688,0.303893,0.788024,-0.197144,-0.887043,1.059754,...,-0.472357,-0.213562,0.837594,-0.756061,0.477499,0.269185,0.235384,0.108495,0.202259,3.433987
2016-09-30,-0.412701,-0.073867,-0.637774,-1.678193,-0.463941,-0.731004,-0.923764,-0.940847,-1.428452,-1.055015,...,-1.742435,-1.457597,-1.431642,-1.301270,-1.794905,-1.214835,-0.173332,-1.597285,-0.005782,NaN

In [ ]:
df.resample('1M').agg(lambda x:skew(x))

,c_feat_0,c_feat_1,c_feat_2,c_feat_3,c_feat_4,c_feat_5,c_feat_6,c_feat_7,c_feat_8,c_feat_9,...,c_feat_50,c_feat_51,c_feat_52,c_feat_53,c_feat_54,c_feat_55,c_feat_56,c_feat_57,c_feat_58,temperatura
date,,,,,,,,,,,,,,,,,,,,,
2010-12-31,1.415046,0.438703,0.956127,1.315680,1.204588,1.045290,0.873297,1.161851,1.387314,1.195628,...,1.413077,1.335350,0.468777,0.469761,0.780203,0.864130,1.519458,0.766499,1.110171,0.506298
2011-01-31,0.723445,0.942476,0.760333,0.811127,1.376330,1.059856,-0.265510,0.513923,0.673694,0.946485,...,1.062092,1.614988,0.765364,0.948482,0.677104,1.161598,1.339523,0.876393,2.317539,0.885165
2011-02-28,2.113309,3.652843,2.277630,2.172100,1.231538,0.179475,0.457305,1.617195,0.841571,1.183152,...,0.512172,0.421438,0.786301,0.447631,0.784766,0.993058,2.044869,1.788771,2.420080,1.646509
2011-03-31,2.215656,2.696651,2.517018,2.760120,1.670859,1.358028,0.957422,1.095307,1.049459,0.769887,...,0.076838,0.591248,-0.107453,0.290305,0.675892,0.705734,0.925661,1.952923,1.179897,2.681663
2011-04-30,0.603328,0.007689,0.386221,0.264691,0.854676,0.469238,0.357604,0.741809,1.024478,0.733357,...,2.386577,1.030415,0.831310,0.096651,1.029911,1.464391,1.335984,1.622440,1.151155,0.592524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-05-31,1.938851,2.292712,2.209436,2.597156,1.587158,1.872410,0.946942,0.897831,0.687225,0.560142,...,0.357336,0.769497,0.357401,0.477596,0.646204,0.938168,0.890154,1.976845,0.976734,2.881937
2016-06-30,0.990353,0.234543,0.944766,0.668461,0.282094,0.174617,0.455806,0.936498,0.981071,0.824261,...,2.750074,0.837980,1.312270,0.228843,1.034735,1.081498,0.420251,0.616621,0.816477,0.778930
2016-07-31,1.588350,1.721530,1.206870,0.867211,2.172957,0.695278,-0.096831,0.755030,1.065598,1.434613,...,3.022969,2.178039,1.555690,1.398448,2.207578,2.880953,2.506156,2.950641,2.028204,0.832342
2016-08-31,0.699933,1.017878,0.297538,0.292479,0.049117,0.621809,1.011152,0.650246,0.308527,1.081641,...,0.582188,0.289148,1.083649,0.286262,1.032042,0.738430,0.877436,0.787939,0.695773,1.656881
2016-09-30,0.840348,-1.176023,0.951964,0.264718,0.933482,-0.607161,0.322707,0.682197,-0.108719,0.093980,...,-0.261640,-0.148311,-0.108683,0.206701,0.346631,-0.091884,1.233508,0.113752,1.283583,NaN